<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://service.programacionparaaprender.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://service.programacionparaaprender.com" xmlns:intf="http://service.programacionparaaprender.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://service.programacionparaaprender.com" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="resultado">
    <complexType/>
   </element>
   <element name="resultadoResponse">
    <complexType>
     <sequence>
      <element name="resultadoReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="resultadoRequest">

      <wsdl:part element="impl:resultado" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="resultadoResponse">

      <wsdl:part element="impl:resultadoResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="HolaWebService">

      <wsdl:operation name="resultado">

         <wsdl:input message="impl:resultadoRequest" name="resultadoRequest">

       </wsdl:input>

         <wsdl:output message="impl:resultadoResponse" name="resultadoResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="HolaWebServiceSoapBinding" type="impl:HolaWebService">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="resultado">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="resultadoRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="resultadoResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="HolaWebServiceService">

      <wsdl:port binding="impl:HolaWebServiceSoapBinding" name="HolaWebService">

         <wsdlsoap:address location="http://localhost:8080/PrimerWS/services/HolaWebService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
